name: setup-node
description: 'Setup Node.js and install dependencies'
runs:
  using: 'composite'
  steps:
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: cache dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: install dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: npm ci


