name: Deploy to Nginx Webserver

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Deploy to Nginx Webserver
        env:
          SSH_KEY: ${{ secrets.HOST_DEPLOY_KEY }}
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y openssh-client
          
          # Create SSH directory and key file
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Disable strict host key checking
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          
          # Deploy files
          rsync -avz --delete dist/ carson@cartt.one:/home/carson/www/files
          
          # Restart Nginx
          sshpass -p "$SUDO_PASSWORD" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa carson@cartt.one "echo $SUDO_PASSWORD | sudo -S systemctl restart nginx"